version: '3.0.3'
services:
  mysql:
    image: mysql:5.7
    platform: linux/amd64
    ports:
      - "3309:3306"
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=app_db
      - MYSQL_ROOT_PASSWORD=toor

#  zookeeper:
#    image: confluentinc/cp-zookeeper:5.3.1
#    container_name: zookeeper
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 2181
#      ZOOKEEPER_TICK_TIME: 2000
#    ports:
#    - "2181:2181"
#  kafka:
#    image: confluentinc/cp-kafka:5.3.1
#    container_name: kafka
#    ports: [ "9092:9092" ]
#    environment:
#      KAFKA_BROKER_ID: 1
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
#      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT